name: Deploy

on:
  push:
    branches: [ "1.23.0.nyaya" ]

jobs:
  build:
    name: "Build"
    runs-on: ubuntu-latest

    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Install JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Clojure tooling
        uses: DeLaGuardo/setup-clojure@10.2
        with:
          cli: 1.11.1.1257

      - name: Publish package
        run: lein deploy github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
